# Generated by Django 6.0.4 on 2026-05-09 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tracker', '0002_book_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rate this book from 1 to 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
