# Generated by Django 6.0.4 on 2026-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tracker', '0004_booknote'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknote',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('themes', 'Themes'), ('structure', 'Structure'), ('character_arcs', 'Character Arcs'), ('personal_reflections', 'Personal Reflections')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='booknote',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
